# Generated by Django 2.2.5 on 2019-12-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
