# Generated by Django 2.2.5 on 2019-12-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tag',
            field=models.CharField(default='#SOso', max_length=50),
            preserve_default=False,
        ),
    ]
