# Generated by Django 2.2.5 on 2019-12-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_articles_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='location',
            field=models.CharField(default=(54.517792, 36.267489), max_length=100),
            preserve_default=False,
        ),
    ]
